### ISSUE TITLE
Cannot read property 'initializer' of undefined

### ISSUE THREAD

**Issue by IsaacHub** [puku0x/angular-pwa-sample#8]
I have done this in my existing project
I executed `ng add @angular/pwa` and it went all good, next I executed `ng generate app-shell` then I got the following error:
`Cannot read property 'initializer' of undefined`

Do you know how to resolve this?

```
Angular CLI: 10.0.0
Node: 14.4.0
OS: win32 x64

Angular: 10.0.1
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

```

**Comment by IsaacHub** [comment]
Do I need to convert my project to an Universal app before executing app-shell?

**Comment by puku0x** [comment]
@IsaacHub 
It means you have to check the object providing `.initializer` (I guess it is in `AppModule` or `AppComponent`) is `undefined` or not.

One of the cons of app-shell is that it is built on Universal and sometimes you should check the platform running the modules/components on.

```ts
import { Inject, PLATFORM_ID } from '@angular/core';
import { isPlatformBrowser, isPlatformServer } from '@angular/common';
```
```ts
constructor(@Inject(PLATFORM_ID) private platformId) {}
```
```ts
if (isPlatformBrowser(this.platformId)) {
  // in case the app needs `window` object
}
if (isPlatformServer(this.platformId)) {
  // in case the app needs `global` object
}
```
