### ISSUE TITLE
Need help with understanding the server folder

### ISSUE THREAD

**Issue by IsaacHub** [puku0x/angular-pwa-sample#9]
**This is not an issue**
Hi, I built it using `ng run my-app:app-shell:production` then I got `dist/my-app/server` 

I'm curious what can be done with this, 

Is this an angular universal app? 
Can we deploy this `server` folder to a `node js` deployment server?
What is the use case of `server` folder?

**Comment by puku0x** [comment]
@IsaacHub
Yes, the `server` folder is an Angular Universal app folder.

I've never deployed the folder but the `main.js` generated by the command seems not to be deployable as a Node.js application because it doesn't listen request but just exit after `node dist/my-app/server/main.js`.
